// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Epoch struct {
	ID               int64 `json:"id"`
	EpochNumber      int64 `json:"epoch_number"`
	ValidatorBalance int64 `json:"validator_balance"`
	PaidOut          bool  `json:"paid_out"`
}

type Payout struct {
	ID              int64  `json:"id"`
	EpochID         int64  `json:"epoch_id"`
	StakerAddress   string `json:"staker_address"`
	PayoutTxHash    string `json:"payout_tx_hash"`
	PayoutCompleted bool   `json:"payout_completed"`
}

type PoolPayout struct {
	ID            int64   `json:"id"`
	EpochID       int64   `json:"epoch_id"`
	Amount        float64 `json:"amount"`
	FeePercentage float64 `json:"fee_percentage"`
	FeeAmount     float64 `json:"fee_amount"`
	FeeTxHash     string  `json:"fee_tx_hash"`
}

type Staker struct {
	ID      int64  `json:"id"`
	EpochID int64  `json:"epoch_id"`
	Address string `json:"address"`
	Stake   int64  `json:"stake"`
}
