// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Cursor struct {
	Name   string `json:"name"`
	Height int64  `json:"height"`
}

type Epoch struct {
	Number     int64        `json:"number"`
	NumStakers int64        `json:"num_stakers"`
	Balance    int64        `json:"balance"`
	Status     string       `json:"status"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Payslip struct {
	ID          int64          `json:"id"`
	BatchNumber int64          `json:"batch_number"`
	Address     string         `json:"address"`
	Amount      int64          `json:"amount"`
	Status      string         `json:"status"`
	TxHash      sql.NullString `json:"tx_hash"`
}

type PolicyConstant struct {
	ID                        int64        `json:"id"`
	StakingContractAddress    string       `json:"staking_contract_address"`
	TransactionValidityWindow int64        `json:"transaction_validity_window"`
	BlocksPerBatch            int64        `json:"blocks_per_batch"`
	BatchesPerEpoch           int64        `json:"batches_per_epoch"`
	BlocksPerEpoch            int64        `json:"blocks_per_epoch"`
	ValidatorDeposit          int64        `json:"validator_deposit"`
	MinimumStake              int64        `json:"minimum_stake"`
	TotalSupply               int64        `json:"total_supply"`
	BlockSeparationTime       int64        `json:"block_separation_time"`
	JailEpochs                int64        `json:"jail_epochs"`
	GenesisBlockNumber        int64        `json:"genesis_block_number"`
	CreatedAt                 sql.NullTime `json:"created_at"`
}

type Reward struct {
	BatchNumber int64        `json:"batch_number"`
	EpochNumber int64        `json:"epoch_number"`
	Amount      int64        `json:"amount"`
	PoolFee     int64        `json:"pool_fee"`
	NumStakers  int64        `json:"num_stakers"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Staker struct {
	EpochNumber int64   `json:"epoch_number"`
	Address     string  `json:"address"`
	Stake       int64   `json:"stake"`
	Percentage  float64 `json:"percentage"`
}

type Transaction struct {
	Hash        string       `json:"hash"`
	Address     string       `json:"address"`
	Amount      int64        `json:"amount"`
	Status      string       `json:"status"`
	SubmittedAt sql.NullTime `json:"submitted_at"`
}

type ValidatorAction struct {
	ID          int64          `json:"id"`
	Action      string         `json:"action"`
	AttemptedAt sql.NullTime   `json:"attempted_at"`
	TxHash      sql.NullString `json:"tx_hash"`
	Outcome     string         `json:"outcome"`
}
