// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CancelRequestedValidatorAction = `-- name: CancelRequestedValidatorAction :one
UPDATE validator_actions
SET state = 'cancelled', outcome = 'cancelled', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND state = 'requested'
RETURNING id
`

func (q *Queries) CancelRequestedValidatorAction(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CancelRequestedValidatorAction, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const CompleteSubmittedValidatorAction = `-- name: CompleteSubmittedValidatorAction :one
UPDATE validator_actions
SET state = ?, updated_at = CURRENT_TIMESTAMP, error_summary = ?
WHERE id = ? AND state = 'submitted'
RETURNING id
`

type CompleteSubmittedValidatorActionParams struct {
	State        sql.NullString `json:"state"`
	ErrorSummary sql.NullString `json:"error_summary"`
	ID           int64          `json:"id"`
}

func (q *Queries) CompleteSubmittedValidatorAction(ctx context.Context, arg CompleteSubmittedValidatorActionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CompleteSubmittedValidatorAction, arg.State, arg.ErrorSummary, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const CountPayoutTransactions = `-- name: CountPayoutTransactions :one
SELECT COUNT(*) FROM transactions WHERE (? IS NULL OR status = ?)
`

type CountPayoutTransactionsParams struct {
	Column1 interface{} `json:"column_1"`
	Status  string      `json:"status"`
}

func (q *Queries) CountPayoutTransactions(ctx context.Context, arg CountPayoutTransactionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPayoutTransactions, arg.Column1, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountValidatorActions = `-- name: CountValidatorActions :one
SELECT COUNT(*) FROM validator_actions WHERE (? IS NULL OR COALESCE(state, outcome) = ?)
`

type CountValidatorActionsParams struct {
	Column1 interface{}    `json:"column_1"`
	State   sql.NullString `json:"state"`
}

func (q *Queries) CountValidatorActions(ctx context.Context, arg CountValidatorActionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountValidatorActions, arg.Column1, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const EpochExists = `-- name: EpochExists :one
SELECT EXISTS(SELECT 1 FROM epochs WHERE number = ?)
`

func (q *Queries) EpochExists(ctx context.Context, number int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, EpochExists, number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const FinalizeCompletedEpochs = `-- name: FinalizeCompletedEpochs :many
UPDATE epochs SET status = 'completed' WHERE number IN (
    SELECT r.epoch_number
    FROM rewards AS r
    INNER JOIN (
        SELECT batch_number, COUNT(*) AS total, SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS done
        FROM payslips
        GROUP BY batch_number
    ) AS p ON p.batch_number = r.batch_number
    INNER JOIN epochs AS e ON e.number = r.epoch_number
    WHERE e.status = 'in_progress'
    GROUP BY r.epoch_number
    HAVING SUM(p.total) = SUM(p.done)
) RETURNING number
`

func (q *Queries) FinalizeCompletedEpochs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, FinalizeCompletedEpochs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FinalizePayslips = `-- name: FinalizePayslips :exec
UPDATE payslips SET status = 'completed' WHERE tx_hash = ?
`

func (q *Queries) FinalizePayslips(ctx context.Context, txHash sql.NullString) error {
	_, err := q.db.ExecContext(ctx, FinalizePayslips, txHash)
	return err
}

const GetCurrentEpochSnapshot = `-- name: GetCurrentEpochSnapshot :one
SELECT num_stakers, balance FROM epochs
WHERE status = 'in_progress'
ORDER BY number DESC
LIMIT 1
`

type GetCurrentEpochSnapshotRow struct {
	NumStakers int64 `json:"num_stakers"`
	Balance    int64 `json:"balance"`
}

func (q *Queries) GetCurrentEpochSnapshot(ctx context.Context) (GetCurrentEpochSnapshotRow, error) {
	row := q.db.QueryRowContext(ctx, GetCurrentEpochSnapshot)
	var i GetCurrentEpochSnapshotRow
	err := row.Scan(&i.NumStakers, &i.Balance)
	return i, err
}

const GetCursor = `-- name: GetCursor :one
SELECT height FROM cursor WHERE name = ?
`

func (q *Queries) GetCursor(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetCursor, name)
	var height int64
	err := row.Scan(&height)
	return height, err
}

const GetEligibleForPayout = `-- name: GetEligibleForPayout :many
SELECT address, CAST(SUM(amount) AS INTEGER) AS total
FROM payslips
WHERE status = 'pending'
GROUP BY address
HAVING SUM(amount) >= ?
`

type GetEligibleForPayoutRow struct {
	Address string `json:"address"`
	Total   int64  `json:"total"`
}

func (q *Queries) GetEligibleForPayout(ctx context.Context, amount int64) ([]GetEligibleForPayoutRow, error) {
	rows, err := q.db.QueryContext(ctx, GetEligibleForPayout, amount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEligibleForPayoutRow{}
	for rows.Next() {
		var i GetEligibleForPayoutRow
		if err := rows.Scan(&i.Address, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEpochByNumber = `-- name: GetEpochByNumber :one
SELECT number, num_stakers, balance, status FROM epochs WHERE number = ?
`

type GetEpochByNumberRow struct {
	Number     int64  `json:"number"`
	NumStakers int64  `json:"num_stakers"`
	Balance    int64  `json:"balance"`
	Status     string `json:"status"`
}

func (q *Queries) GetEpochByNumber(ctx context.Context, number int64) (GetEpochByNumberRow, error) {
	row := q.db.QueryRowContext(ctx, GetEpochByNumber, number)
	var i GetEpochByNumberRow
	err := row.Scan(
		&i.Number,
		&i.NumStakers,
		&i.Balance,
		&i.Status,
	)
	return i, err
}

const GetEpochStatus = `-- name: GetEpochStatus :one
SELECT status, num_stakers FROM epochs WHERE number = ?
`

type GetEpochStatusRow struct {
	Status     string `json:"status"`
	NumStakers int64  `json:"num_stakers"`
}

func (q *Queries) GetEpochStatus(ctx context.Context, number int64) (GetEpochStatusRow, error) {
	row := q.db.QueryRowContext(ctx, GetEpochStatus, number)
	var i GetEpochStatusRow
	err := row.Scan(&i.Status, &i.NumStakers)
	return i, err
}

const GetLatestEpoch = `-- name: GetLatestEpoch :one
SELECT number, num_stakers, balance, status FROM epochs ORDER BY number DESC LIMIT 1
`

type GetLatestEpochRow struct {
	Number     int64  `json:"number"`
	NumStakers int64  `json:"num_stakers"`
	Balance    int64  `json:"balance"`
	Status     string `json:"status"`
}

func (q *Queries) GetLatestEpoch(ctx context.Context) (GetLatestEpochRow, error) {
	row := q.db.QueryRowContext(ctx, GetLatestEpoch)
	var i GetLatestEpochRow
	err := row.Scan(
		&i.Number,
		&i.NumStakers,
		&i.Balance,
		&i.Status,
	)
	return i, err
}

const GetLatestPolicyConstants = `-- name: GetLatestPolicyConstants :one
SELECT staking_contract_address, transaction_validity_window, blocks_per_batch,
    batches_per_epoch, blocks_per_epoch, validator_deposit, minimum_stake,
    total_supply, block_separation_time, jail_epochs, genesis_block_number
FROM policy_constants ORDER BY id DESC LIMIT 1
`

type GetLatestPolicyConstantsRow struct {
	StakingContractAddress    string `json:"staking_contract_address"`
	TransactionValidityWindow int64  `json:"transaction_validity_window"`
	BlocksPerBatch            int64  `json:"blocks_per_batch"`
	BatchesPerEpoch           int64  `json:"batches_per_epoch"`
	BlocksPerEpoch            int64  `json:"blocks_per_epoch"`
	ValidatorDeposit          int64  `json:"validator_deposit"`
	MinimumStake              int64  `json:"minimum_stake"`
	TotalSupply               int64  `json:"total_supply"`
	BlockSeparationTime       int64  `json:"block_separation_time"`
	JailEpochs                int64  `json:"jail_epochs"`
	GenesisBlockNumber        int64  `json:"genesis_block_number"`
}

func (q *Queries) GetLatestPolicyConstants(ctx context.Context) (GetLatestPolicyConstantsRow, error) {
	row := q.db.QueryRowContext(ctx, GetLatestPolicyConstants)
	var i GetLatestPolicyConstantsRow
	err := row.Scan(
		&i.StakingContractAddress,
		&i.TransactionValidityWindow,
		&i.BlocksPerBatch,
		&i.BatchesPerEpoch,
		&i.BlocksPerEpoch,
		&i.ValidatorDeposit,
		&i.MinimumStake,
		&i.TotalSupply,
		&i.BlockSeparationTime,
		&i.JailEpochs,
		&i.GenesisBlockNumber,
	)
	return i, err
}

const GetPayslipStats = `-- name: GetPayslipStats :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END), 0) AS INTEGER) AS pending_count,
    CAST(COALESCE(SUM(CASE WHEN status = 'pending' THEN amount ELSE 0 END), 0) AS INTEGER) AS pending_luna,
    CAST(COALESCE(SUM(CASE WHEN status IN ('out_for_payment', 'awaiting_confirmation') THEN 1 ELSE 0 END), 0) AS INTEGER) AS stuck_count
FROM payslips
`

type GetPayslipStatsRow struct {
	PendingCount int64 `json:"pending_count"`
	PendingLuna  int64 `json:"pending_luna"`
	StuckCount   int64 `json:"stuck_count"`
}

func (q *Queries) GetPayslipStats(ctx context.Context) (GetPayslipStatsRow, error) {
	row := q.db.QueryRowContext(ctx, GetPayslipStats)
	var i GetPayslipStatsRow
	err := row.Scan(&i.PendingCount, &i.PendingLuna, &i.StuckCount)
	return i, err
}

const GetPayslipsForAddress = `-- name: GetPayslipsForAddress :many
SELECT batch_number, amount, status, tx_hash FROM payslips WHERE address = ? ORDER BY batch_number DESC
`

type GetPayslipsForAddressRow struct {
	BatchNumber int64          `json:"batch_number"`
	Amount      int64          `json:"amount"`
	Status      string         `json:"status"`
	TxHash      sql.NullString `json:"tx_hash"`
}

func (q *Queries) GetPayslipsForAddress(ctx context.Context, address string) ([]GetPayslipsForAddressRow, error) {
	rows, err := q.db.QueryContext(ctx, GetPayslipsForAddress, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPayslipsForAddressRow{}
	for rows.Next() {
		var i GetPayslipsForAddressRow
		if err := rows.Scan(
			&i.BatchNumber,
			&i.Amount,
			&i.Status,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPendingTransactions = `-- name: GetPendingTransactions :many
SELECT hash, address, amount FROM transactions WHERE status = 'awaiting_confirmation'
`

type GetPendingTransactionsRow struct {
	Hash    string `json:"hash"`
	Address string `json:"address"`
	Amount  int64  `json:"amount"`
}

func (q *Queries) GetPendingTransactions(ctx context.Context) ([]GetPendingTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetPendingTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingTransactionsRow{}
	for rows.Next() {
		var i GetPendingTransactionsRow
		if err := rows.Scan(&i.Hash, &i.Address, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRequestedValidatorActions = `-- name: GetRequestedValidatorActions :many
SELECT id, action
FROM validator_actions
WHERE state = 'requested' OR (state IS NULL AND outcome = 'requested')
ORDER BY id
`

type GetRequestedValidatorActionsRow struct {
	ID     int64  `json:"id"`
	Action string `json:"action"`
}

func (q *Queries) GetRequestedValidatorActions(ctx context.Context) ([]GetRequestedValidatorActionsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetRequestedValidatorActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRequestedValidatorActionsRow{}
	for rows.Next() {
		var i GetRequestedValidatorActionsRow
		if err := rows.Scan(&i.ID, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRuntimeStatus = `-- name: GetRuntimeStatus :one
SELECT id, heartbeat_at, daemon_version, config_hash, derived_validator_address, validator_state, last_processed_height, chain_head, last_tick_ms, rpc_ok, readiness_error FROM runtime_status WHERE id = 1
`

func (q *Queries) GetRuntimeStatus(ctx context.Context) (RuntimeStatus, error) {
	row := q.db.QueryRowContext(ctx, GetRuntimeStatus)
	var i RuntimeStatus
	err := row.Scan(
		&i.ID,
		&i.HeartbeatAt,
		&i.DaemonVersion,
		&i.ConfigHash,
		&i.DerivedValidatorAddress,
		&i.ValidatorState,
		&i.LastProcessedHeight,
		&i.ChainHead,
		&i.LastTickMs,
		&i.RpcOk,
		&i.ReadinessError,
	)
	return i, err
}

const GetStakerLatest = `-- name: GetStakerLatest :one
SELECT epoch_number, stake, percentage FROM stakers WHERE address = ? ORDER BY epoch_number DESC LIMIT 1
`

type GetStakerLatestRow struct {
	EpochNumber int64   `json:"epoch_number"`
	Stake       int64   `json:"stake"`
	Percentage  float64 `json:"percentage"`
}

func (q *Queries) GetStakerLatest(ctx context.Context, address string) (GetStakerLatestRow, error) {
	row := q.db.QueryRowContext(ctx, GetStakerLatest, address)
	var i GetStakerLatestRow
	err := row.Scan(&i.EpochNumber, &i.Stake, &i.Percentage)
	return i, err
}

const GetStakersForEpoch = `-- name: GetStakersForEpoch :many
SELECT address, stake, percentage FROM stakers WHERE epoch_number = ?
`

type GetStakersForEpochRow struct {
	Address    string  `json:"address"`
	Stake      int64   `json:"stake"`
	Percentage float64 `json:"percentage"`
}

func (q *Queries) GetStakersForEpoch(ctx context.Context, epochNumber int64) ([]GetStakersForEpochRow, error) {
	rows, err := q.db.QueryContext(ctx, GetStakersForEpoch, epochNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStakersForEpochRow{}
	for rows.Next() {
		var i GetStakersForEpochRow
		if err := rows.Scan(&i.Address, &i.Stake, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStuckPayslips = `-- name: GetStuckPayslips :many
SELECT p.id, p.batch_number, p.address, p.amount, p.status, p.tx_hash, t.submitted_at
FROM payslips p
LEFT JOIN transactions t ON t.hash = p.tx_hash
WHERE p.status IN ('out_for_payment', 'awaiting_confirmation')
ORDER BY p.id
`

type GetStuckPayslipsRow struct {
	ID          int64          `json:"id"`
	BatchNumber int64          `json:"batch_number"`
	Address     string         `json:"address"`
	Amount      int64          `json:"amount"`
	Status      string         `json:"status"`
	TxHash      sql.NullString `json:"tx_hash"`
	SubmittedAt sql.NullTime   `json:"submitted_at"`
}

func (q *Queries) GetStuckPayslips(ctx context.Context) ([]GetStuckPayslipsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetStuckPayslips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStuckPayslipsRow{}
	for rows.Next() {
		var i GetStuckPayslipsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchNumber,
			&i.Address,
			&i.Amount,
			&i.Status,
			&i.TxHash,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTransactionsForAddress = `-- name: GetTransactionsForAddress :many
SELECT hash, amount, status, submitted_at FROM transactions WHERE address = ? ORDER BY submitted_at DESC
`

type GetTransactionsForAddressRow struct {
	Hash        string       `json:"hash"`
	Amount      int64        `json:"amount"`
	Status      string       `json:"status"`
	SubmittedAt sql.NullTime `json:"submitted_at"`
}

func (q *Queries) GetTransactionsForAddress(ctx context.Context, address string) ([]GetTransactionsForAddressRow, error) {
	rows, err := q.db.QueryContext(ctx, GetTransactionsForAddress, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsForAddressRow{}
	for rows.Next() {
		var i GetTransactionsForAddressRow
		if err := rows.Scan(
			&i.Hash,
			&i.Amount,
			&i.Status,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetValidatorAction = `-- name: GetValidatorAction :one
SELECT id, action, attempted_at, tx_hash, outcome, requested_by, requested_at, updated_at, state, error_summary, correlation_id FROM validator_actions WHERE id = ?
`

func (q *Queries) GetValidatorAction(ctx context.Context, id int64) (ValidatorAction, error) {
	row := q.db.QueryRowContext(ctx, GetValidatorAction, id)
	var i ValidatorAction
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.AttemptedAt,
		&i.TxHash,
		&i.Outcome,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.UpdatedAt,
		&i.State,
		&i.ErrorSummary,
		&i.CorrelationID,
	)
	return i, err
}

const HasOutstandingValidatorAction = `-- name: HasOutstandingValidatorAction :one
SELECT EXISTS(
    SELECT 1
    FROM validator_actions
    WHERE action = ?
      AND (
        state IN ('requested', 'processing', 'submitted')
        OR (state IS NULL AND outcome IN ('requested', 'pending'))
      )
)
`

func (q *Queries) HasOutstandingValidatorAction(ctx context.Context, action string) (bool, error) {
	row := q.db.QueryRowContext(ctx, HasOutstandingValidatorAction, action)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const HasPendingValidatorAction = `-- name: HasPendingValidatorAction :one
SELECT EXISTS(SELECT 1 FROM validator_actions WHERE action = ? AND outcome = 'pending')
`

func (q *Queries) HasPendingValidatorAction(ctx context.Context, action string) (bool, error) {
	row := q.db.QueryRowContext(ctx, HasPendingValidatorAction, action)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const InsertAlertDelivery = `-- name: InsertAlertDelivery :one
INSERT INTO alert_deliveries (channel, alert_type, destination, state, response_summary, correlation_id)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertAlertDeliveryParams struct {
	Channel         string         `json:"channel"`
	AlertType       string         `json:"alert_type"`
	Destination     string         `json:"destination"`
	State           string         `json:"state"`
	ResponseSummary sql.NullString `json:"response_summary"`
	CorrelationID   sql.NullString `json:"correlation_id"`
}

func (q *Queries) InsertAlertDelivery(ctx context.Context, arg InsertAlertDeliveryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertAlertDelivery,
		arg.Channel,
		arg.AlertType,
		arg.Destination,
		arg.State,
		arg.ResponseSummary,
		arg.CorrelationID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (action_type, address, amount, fee, kind, status, intent_data)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertAuditLogParams struct {
	ActionType string         `json:"action_type"`
	Address    string         `json:"address"`
	Amount     int64          `json:"amount"`
	Fee        int64          `json:"fee"`
	Kind       string         `json:"kind"`
	Status     string         `json:"status"`
	IntentData sql.NullString `json:"intent_data"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertAuditLog,
		arg.ActionType,
		arg.Address,
		arg.Amount,
		arg.Fee,
		arg.Kind,
		arg.Status,
		arg.IntentData,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertConfigRevision = `-- name: InsertConfigRevision :one
INSERT INTO config_revisions (actor_address, before_json, after_json, validation_state, write_state, config_hash)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertConfigRevisionParams struct {
	ActorAddress    sql.NullString `json:"actor_address"`
	BeforeJson      sql.NullString `json:"before_json"`
	AfterJson       sql.NullString `json:"after_json"`
	ValidationState sql.NullString `json:"validation_state"`
	WriteState      sql.NullString `json:"write_state"`
	ConfigHash      sql.NullString `json:"config_hash"`
}

func (q *Queries) InsertConfigRevision(ctx context.Context, arg InsertConfigRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertConfigRevision,
		arg.ActorAddress,
		arg.BeforeJson,
		arg.AfterJson,
		arg.ValidationState,
		arg.WriteState,
		arg.ConfigHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertEpoch = `-- name: InsertEpoch :exec
INSERT INTO epochs (number, num_stakers, balance, status) VALUES (?, ?, ?, ?)
`

type InsertEpochParams struct {
	Number     int64  `json:"number"`
	NumStakers int64  `json:"num_stakers"`
	Balance    int64  `json:"balance"`
	Status     string `json:"status"`
}

func (q *Queries) InsertEpoch(ctx context.Context, arg InsertEpochParams) error {
	_, err := q.db.ExecContext(ctx, InsertEpoch,
		arg.Number,
		arg.NumStakers,
		arg.Balance,
		arg.Status,
	)
	return err
}

const InsertHealthSnapshot = `-- name: InsertHealthSnapshot :one
INSERT INTO health_snapshots (recorded_at, chain_head, processed_height, tick_ms, validator_state, live_stake, staker_count, pending_payout_count, pending_payout_luna, stuck_payout_count, stuck_payout_luna, wallet_balance, rpc_ok)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertHealthSnapshotParams struct {
	RecordedAt         time.Time `json:"recorded_at"`
	ChainHead          int64     `json:"chain_head"`
	ProcessedHeight    int64     `json:"processed_height"`
	TickMs             int64     `json:"tick_ms"`
	ValidatorState     string    `json:"validator_state"`
	LiveStake          int64     `json:"live_stake"`
	StakerCount        int64     `json:"staker_count"`
	PendingPayoutCount int64     `json:"pending_payout_count"`
	PendingPayoutLuna  int64     `json:"pending_payout_luna"`
	StuckPayoutCount   int64     `json:"stuck_payout_count"`
	StuckPayoutLuna    int64     `json:"stuck_payout_luna"`
	WalletBalance      int64     `json:"wallet_balance"`
	RpcOk              int64     `json:"rpc_ok"`
}

func (q *Queries) InsertHealthSnapshot(ctx context.Context, arg InsertHealthSnapshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertHealthSnapshot,
		arg.RecordedAt,
		arg.ChainHead,
		arg.ProcessedHeight,
		arg.TickMs,
		arg.ValidatorState,
		arg.LiveStake,
		arg.StakerCount,
		arg.PendingPayoutCount,
		arg.PendingPayoutLuna,
		arg.StuckPayoutCount,
		arg.StuckPayoutLuna,
		arg.WalletBalance,
		arg.RpcOk,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertOperatorEvent = `-- name: InsertOperatorEvent :one
INSERT INTO operator_events (severity, category, source, event_type, summary, context_json, actor_address, correlation_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type InsertOperatorEventParams struct {
	Severity      string         `json:"severity"`
	Category      string         `json:"category"`
	Source        string         `json:"source"`
	EventType     string         `json:"event_type"`
	Summary       string         `json:"summary"`
	ContextJson   sql.NullString `json:"context_json"`
	ActorAddress  sql.NullString `json:"actor_address"`
	CorrelationID sql.NullString `json:"correlation_id"`
}

func (q *Queries) InsertOperatorEvent(ctx context.Context, arg InsertOperatorEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertOperatorEvent,
		arg.Severity,
		arg.Category,
		arg.Source,
		arg.EventType,
		arg.Summary,
		arg.ContextJson,
		arg.ActorAddress,
		arg.CorrelationID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertPayslip = `-- name: InsertPayslip :exec
INSERT INTO payslips (batch_number, address, amount, status) VALUES (?, ?, ?, ?)
`

type InsertPayslipParams struct {
	BatchNumber int64  `json:"batch_number"`
	Address     string `json:"address"`
	Amount      int64  `json:"amount"`
	Status      string `json:"status"`
}

func (q *Queries) InsertPayslip(ctx context.Context, arg InsertPayslipParams) error {
	_, err := q.db.ExecContext(ctx, InsertPayslip,
		arg.BatchNumber,
		arg.Address,
		arg.Amount,
		arg.Status,
	)
	return err
}

const InsertPolicyConstants = `-- name: InsertPolicyConstants :exec
INSERT INTO policy_constants (
    staking_contract_address, transaction_validity_window, blocks_per_batch,
    batches_per_epoch, blocks_per_epoch, validator_deposit, minimum_stake,
    total_supply, block_separation_time, jail_epochs, genesis_block_number
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPolicyConstantsParams struct {
	StakingContractAddress    string `json:"staking_contract_address"`
	TransactionValidityWindow int64  `json:"transaction_validity_window"`
	BlocksPerBatch            int64  `json:"blocks_per_batch"`
	BatchesPerEpoch           int64  `json:"batches_per_epoch"`
	BlocksPerEpoch            int64  `json:"blocks_per_epoch"`
	ValidatorDeposit          int64  `json:"validator_deposit"`
	MinimumStake              int64  `json:"minimum_stake"`
	TotalSupply               int64  `json:"total_supply"`
	BlockSeparationTime       int64  `json:"block_separation_time"`
	JailEpochs                int64  `json:"jail_epochs"`
	GenesisBlockNumber        int64  `json:"genesis_block_number"`
}

func (q *Queries) InsertPolicyConstants(ctx context.Context, arg InsertPolicyConstantsParams) error {
	_, err := q.db.ExecContext(ctx, InsertPolicyConstants,
		arg.StakingContractAddress,
		arg.TransactionValidityWindow,
		arg.BlocksPerBatch,
		arg.BatchesPerEpoch,
		arg.BlocksPerEpoch,
		arg.ValidatorDeposit,
		arg.MinimumStake,
		arg.TotalSupply,
		arg.BlockSeparationTime,
		arg.JailEpochs,
		arg.GenesisBlockNumber,
	)
	return err
}

const InsertRequestedValidatorAction = `-- name: InsertRequestedValidatorAction :one
INSERT INTO validator_actions (action, outcome, state, requested_by, requested_at, updated_at, correlation_id)
SELECT ?1, 'requested', 'requested', ?2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?3
WHERE NOT EXISTS (
    SELECT 1
    FROM validator_actions
    WHERE action = ?1
      AND (
        state IN ('requested', 'processing', 'submitted')
        OR (state IS NULL AND outcome IN ('requested', 'pending'))
      )
)
RETURNING id
`

type InsertRequestedValidatorActionParams struct {
	Action        string         `json:"action"`
	RequestedBy   sql.NullString `json:"requested_by"`
	CorrelationID sql.NullString `json:"correlation_id"`
}

func (q *Queries) InsertRequestedValidatorAction(ctx context.Context, arg InsertRequestedValidatorActionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertRequestedValidatorAction, arg.Action, arg.RequestedBy, arg.CorrelationID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertReward = `-- name: InsertReward :exec
INSERT INTO rewards (batch_number, epoch_number, amount, pool_fee, num_stakers)
VALUES (?, ?, ?, ?, ?)
`

type InsertRewardParams struct {
	BatchNumber int64 `json:"batch_number"`
	EpochNumber int64 `json:"epoch_number"`
	Amount      int64 `json:"amount"`
	PoolFee     int64 `json:"pool_fee"`
	NumStakers  int64 `json:"num_stakers"`
}

func (q *Queries) InsertReward(ctx context.Context, arg InsertRewardParams) error {
	_, err := q.db.ExecContext(ctx, InsertReward,
		arg.BatchNumber,
		arg.EpochNumber,
		arg.Amount,
		arg.PoolFee,
		arg.NumStakers,
	)
	return err
}

const InsertStaker = `-- name: InsertStaker :exec
INSERT INTO stakers (epoch_number, address, stake, percentage) VALUES (?, ?, ?, ?)
`

type InsertStakerParams struct {
	EpochNumber int64   `json:"epoch_number"`
	Address     string  `json:"address"`
	Stake       int64   `json:"stake"`
	Percentage  float64 `json:"percentage"`
}

func (q *Queries) InsertStaker(ctx context.Context, arg InsertStakerParams) error {
	_, err := q.db.ExecContext(ctx, InsertStaker,
		arg.EpochNumber,
		arg.Address,
		arg.Stake,
		arg.Percentage,
	)
	return err
}

const InsertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (hash, address, amount, status) VALUES (?, ?, ?, ?)
`

type InsertTransactionParams struct {
	Hash    string `json:"hash"`
	Address string `json:"address"`
	Amount  int64  `json:"amount"`
	Status  string `json:"status"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, InsertTransaction,
		arg.Hash,
		arg.Address,
		arg.Amount,
		arg.Status,
	)
	return err
}

const InsertValidatorAction = `-- name: InsertValidatorAction :exec
INSERT INTO validator_actions (action, tx_hash, outcome) VALUES (?, ?, ?)
`

type InsertValidatorActionParams struct {
	Action  string         `json:"action"`
	TxHash  sql.NullString `json:"tx_hash"`
	Outcome string         `json:"outcome"`
}

func (q *Queries) InsertValidatorAction(ctx context.Context, arg InsertValidatorActionParams) error {
	_, err := q.db.ExecContext(ctx, InsertValidatorAction, arg.Action, arg.TxHash, arg.Outcome)
	return err
}

const InsertValidatorActionWithState = `-- name: InsertValidatorActionWithState :one
INSERT INTO validator_actions (action, outcome, state, requested_by, requested_at, updated_at, correlation_id)
VALUES (?, 'requested', ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?)
RETURNING id
`

type InsertValidatorActionWithStateParams struct {
	Action        string         `json:"action"`
	State         sql.NullString `json:"state"`
	RequestedBy   sql.NullString `json:"requested_by"`
	CorrelationID sql.NullString `json:"correlation_id"`
}

func (q *Queries) InsertValidatorActionWithState(ctx context.Context, arg InsertValidatorActionWithStateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertValidatorActionWithState,
		arg.Action,
		arg.State,
		arg.RequestedBy,
		arg.CorrelationID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ListApprovedAuditLogs = `-- name: ListApprovedAuditLogs :many
SELECT id, action_type, address, amount, fee, kind, status, intent_data, created_at
FROM audit_logs
WHERE status = 'approved'
ORDER BY created_at ASC
`

type ListApprovedAuditLogsRow struct {
	ID         int64          `json:"id"`
	ActionType string         `json:"action_type"`
	Address    string         `json:"address"`
	Amount     int64          `json:"amount"`
	Fee        int64          `json:"fee"`
	Kind       string         `json:"kind"`
	Status     string         `json:"status"`
	IntentData sql.NullString `json:"intent_data"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListApprovedAuditLogs(ctx context.Context) ([]ListApprovedAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListApprovedAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedAuditLogsRow{}
	for rows.Next() {
		var i ListApprovedAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.Address,
			&i.Amount,
			&i.Fee,
			&i.Kind,
			&i.Status,
			&i.IntentData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListConfigRevisions = `-- name: ListConfigRevisions :many
SELECT id, actor_address, before_json, after_json, validation_state, write_state, created_at, activated_at, config_hash FROM config_revisions ORDER BY id DESC
`

func (q *Queries) ListConfigRevisions(ctx context.Context) ([]ConfigRevision, error) {
	rows, err := q.db.QueryContext(ctx, ListConfigRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigRevision{}
	for rows.Next() {
		var i ConfigRevision
		if err := rows.Scan(
			&i.ID,
			&i.ActorAddress,
			&i.BeforeJson,
			&i.AfterJson,
			&i.ValidationState,
			&i.WriteState,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.ConfigHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEpochs = `-- name: ListEpochs :many
SELECT number, num_stakers, balance, status FROM epochs ORDER BY number DESC
`

type ListEpochsRow struct {
	Number     int64  `json:"number"`
	NumStakers int64  `json:"num_stakers"`
	Balance    int64  `json:"balance"`
	Status     string `json:"status"`
}

func (q *Queries) ListEpochs(ctx context.Context) ([]ListEpochsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListEpochs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpochsRow{}
	for rows.Next() {
		var i ListEpochsRow
		if err := rows.Scan(
			&i.Number,
			&i.NumStakers,
			&i.Balance,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOperatorEvents = `-- name: ListOperatorEvents :many
SELECT id, severity, category, source, event_type, summary, context_json, actor_address, correlation_id, created_at FROM operator_events ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListOperatorEventsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListOperatorEvents(ctx context.Context, arg ListOperatorEventsParams) ([]OperatorEvent, error) {
	rows, err := q.db.QueryContext(ctx, ListOperatorEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorEvent{}
	for rows.Next() {
		var i OperatorEvent
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.Category,
			&i.Source,
			&i.EventType,
			&i.Summary,
			&i.ContextJson,
			&i.ActorAddress,
			&i.CorrelationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPayoutTransactions = `-- name: ListPayoutTransactions :many
SELECT hash, address, amount, status, submitted_at FROM transactions WHERE (? IS NULL OR status = ?) ORDER BY submitted_at DESC LIMIT ? OFFSET ?
`

type ListPayoutTransactionsParams struct {
	Column1 interface{} `json:"column_1"`
	Status  string      `json:"status"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListPayoutTransactions(ctx context.Context, arg ListPayoutTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, ListPayoutTransactions,
		arg.Column1,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.Hash,
			&i.Address,
			&i.Amount,
			&i.Status,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPendingAuditLogs = `-- name: ListPendingAuditLogs :many
SELECT id, action_type, address, amount, fee, kind, status, intent_data, created_at
FROM audit_logs
WHERE status = 'pending'
ORDER BY created_at ASC
`

type ListPendingAuditLogsRow struct {
	ID         int64          `json:"id"`
	ActionType string         `json:"action_type"`
	Address    string         `json:"address"`
	Amount     int64          `json:"amount"`
	Fee        int64          `json:"fee"`
	Kind       string         `json:"kind"`
	Status     string         `json:"status"`
	IntentData sql.NullString `json:"intent_data"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListPendingAuditLogs(ctx context.Context) ([]ListPendingAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPendingAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingAuditLogsRow{}
	for rows.Next() {
		var i ListPendingAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.Address,
			&i.Amount,
			&i.Fee,
			&i.Kind,
			&i.Status,
			&i.IntentData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRewardsByEpochRange = `-- name: ListRewardsByEpochRange :many
SELECT epoch_number, SUM(amount) AS total_amount, SUM(pool_fee) AS total_fee, COUNT(*) AS batches
FROM rewards
WHERE epoch_number BETWEEN ? AND ?
GROUP BY epoch_number
ORDER BY epoch_number ASC
`

type ListRewardsByEpochRangeParams struct {
	FromEpochNumber int64 `json:"from_epoch_number"`
	ToEpochNumber   int64 `json:"to_epoch_number"`
}

type ListRewardsByEpochRangeRow struct {
	EpochNumber int64           `json:"epoch_number"`
	TotalAmount sql.NullFloat64 `json:"total_amount"`
	TotalFee    sql.NullFloat64 `json:"total_fee"`
	Batches     int64           `json:"batches"`
}

func (q *Queries) ListRewardsByEpochRange(ctx context.Context, arg ListRewardsByEpochRangeParams) ([]ListRewardsByEpochRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, ListRewardsByEpochRange, arg.FromEpochNumber, arg.ToEpochNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRewardsByEpochRangeRow{}
	for rows.Next() {
		var i ListRewardsByEpochRangeRow
		if err := rows.Scan(
			&i.EpochNumber,
			&i.TotalAmount,
			&i.TotalFee,
			&i.Batches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListValidatorActions = `-- name: ListValidatorActions :many
SELECT id, action, COALESCE(state, outcome) AS state, requested_at, updated_at, tx_hash, error_summary, correlation_id
FROM validator_actions
WHERE (? IS NULL OR COALESCE(state, outcome) = ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListValidatorActionsParams struct {
	Column1 interface{}    `json:"column_1"`
	State   sql.NullString `json:"state"`
	Limit   int64          `json:"limit"`
	Offset  int64          `json:"offset"`
}

type ListValidatorActionsRow struct {
	ID            int64          `json:"id"`
	Action        string         `json:"action"`
	State         string         `json:"state"`
	RequestedAt   sql.NullTime   `json:"requested_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	TxHash        sql.NullString `json:"tx_hash"`
	ErrorSummary  sql.NullString `json:"error_summary"`
	CorrelationID sql.NullString `json:"correlation_id"`
}

func (q *Queries) ListValidatorActions(ctx context.Context, arg ListValidatorActionsParams) ([]ListValidatorActionsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListValidatorActions,
		arg.Column1,
		arg.State,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListValidatorActionsRow{}
	for rows.Next() {
		var i ListValidatorActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.State,
			&i.RequestedAt,
			&i.UpdatedAt,
			&i.TxHash,
			&i.ErrorSummary,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkPayslipsOutForPayment = `-- name: MarkPayslipsOutForPayment :exec
UPDATE payslips SET status = 'out_for_payment' WHERE address = ? AND status = 'pending'
`

func (q *Queries) MarkPayslipsOutForPayment(ctx context.Context, address string) error {
	_, err := q.db.ExecContext(ctx, MarkPayslipsOutForPayment, address)
	return err
}

const MarkValidatorActionProcessing = `-- name: MarkValidatorActionProcessing :one
UPDATE validator_actions
SET state = 'processing', updated_at = CURRENT_TIMESTAMP, error_summary = NULL
WHERE id = ? AND state = 'requested'
RETURNING id
`

func (q *Queries) MarkValidatorActionProcessing(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, MarkValidatorActionProcessing, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const ResetPayslipsOutForPayment = `-- name: ResetPayslipsOutForPayment :exec
UPDATE payslips SET status = 'pending' WHERE address = ? AND status = 'out_for_payment'
`

func (q *Queries) ResetPayslipsOutForPayment(ctx context.Context, address string) error {
	_, err := q.db.ExecContext(ctx, ResetPayslipsOutForPayment, address)
	return err
}

const ResetPayslipsToPending = `-- name: ResetPayslipsToPending :exec
UPDATE payslips SET tx_hash = NULL, status = 'pending' WHERE tx_hash = ?
`

func (q *Queries) ResetPayslipsToPending(ctx context.Context, txHash sql.NullString) error {
	_, err := q.db.ExecContext(ctx, ResetPayslipsToPending, txHash)
	return err
}

const RetryFailedPayoutPayslips = `-- name: RetryFailedPayoutPayslips :many
UPDATE payslips
SET status = 'pending', tx_hash = NULL
WHERE tx_hash = ?1
  AND status = 'failed'
  AND EXISTS (
      SELECT 1
      FROM transactions AS failed_tx
      WHERE failed_tx.hash = ?1
        AND failed_tx.status = 'failed'
  )
  AND NOT EXISTS (
      SELECT 1
      FROM transactions AS active_tx
      WHERE active_tx.address = payslips.address
        AND active_tx.hash != payslips.tx_hash
        AND active_tx.status = 'awaiting_confirmation'
  )
RETURNING id
`

func (q *Queries) RetryFailedPayoutPayslips(ctx context.Context, txHash sql.NullString) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, RetryFailedPayoutPayslips, txHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RewardExists = `-- name: RewardExists :one
SELECT EXISTS(SELECT 1 FROM rewards WHERE batch_number = ?)
`

func (q *Queries) RewardExists(ctx context.Context, batchNumber int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, RewardExists, batchNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const SetEpochStatus = `-- name: SetEpochStatus :exec
UPDATE epochs SET status = ? WHERE number = ?
`

type SetEpochStatusParams struct {
	Status string `json:"status"`
	Number int64  `json:"number"`
}

func (q *Queries) SetEpochStatus(ctx context.Context, arg SetEpochStatusParams) error {
	_, err := q.db.ExecContext(ctx, SetEpochStatus, arg.Status, arg.Number)
	return err
}

const SetPayslipsTransaction = `-- name: SetPayslipsTransaction :exec
UPDATE payslips SET tx_hash = ?, status = 'awaiting_confirmation'
WHERE address = ? AND status = 'out_for_payment'
`

type SetPayslipsTransactionParams struct {
	TxHash  sql.NullString `json:"tx_hash"`
	Address string         `json:"address"`
}

func (q *Queries) SetPayslipsTransaction(ctx context.Context, arg SetPayslipsTransactionParams) error {
	_, err := q.db.ExecContext(ctx, SetPayslipsTransaction, arg.TxHash, arg.Address)
	return err
}

const SetTransactionStatus = `-- name: SetTransactionStatus :exec
UPDATE transactions SET status = ? WHERE hash = ?
`

type SetTransactionStatusParams struct {
	Status string `json:"status"`
	Hash   string `json:"hash"`
}

func (q *Queries) SetTransactionStatus(ctx context.Context, arg SetTransactionStatusParams) error {
	_, err := q.db.ExecContext(ctx, SetTransactionStatus, arg.Status, arg.Hash)
	return err
}

const SetValidatorActionOutcome = `-- name: SetValidatorActionOutcome :exec
UPDATE validator_actions SET outcome = ?, tx_hash = ? WHERE id = ?
`

type SetValidatorActionOutcomeParams struct {
	Outcome string         `json:"outcome"`
	TxHash  sql.NullString `json:"tx_hash"`
	ID      int64          `json:"id"`
}

func (q *Queries) SetValidatorActionOutcome(ctx context.Context, arg SetValidatorActionOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, SetValidatorActionOutcome, arg.Outcome, arg.TxHash, arg.ID)
	return err
}

const StakerExists = `-- name: StakerExists :one
SELECT EXISTS(SELECT 1 FROM stakers WHERE address = ?)
`

func (q *Queries) StakerExists(ctx context.Context, address string) (bool, error) {
	row := q.db.QueryRowContext(ctx, StakerExists, address)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const SubmitValidatorAction = `-- name: SubmitValidatorAction :one
UPDATE validator_actions
SET state = 'submitted', outcome = 'pending', tx_hash = ?, updated_at = CURRENT_TIMESTAMP, error_summary = NULL
WHERE id = ? AND state = 'processing'
RETURNING id
`

type SubmitValidatorActionParams struct {
	TxHash sql.NullString `json:"tx_hash"`
	ID     int64          `json:"id"`
}

func (q *Queries) SubmitValidatorAction(ctx context.Context, arg SubmitValidatorActionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, SubmitValidatorAction, arg.TxHash, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const SumRewardsAmount = `-- name: SumRewardsAmount :one
SELECT CAST(COALESCE(SUM(amount), 0) AS INTEGER) FROM rewards
`

func (q *Queries) SumRewardsAmount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, SumRewardsAmount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const UpdateAuditLogStatus = `-- name: UpdateAuditLogStatus :exec
UPDATE audit_logs
SET status = ?, approved_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAuditLogStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateAuditLogStatus(ctx context.Context, arg UpdateAuditLogStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAuditLogStatus, arg.Status, arg.ID)
	return err
}

const UpdatePayslipStatusFailed = `-- name: UpdatePayslipStatusFailed :exec
UPDATE payslips SET status='failed' WHERE tx_hash=?
`

func (q *Queries) UpdatePayslipStatusFailed(ctx context.Context, txHash sql.NullString) error {
	_, err := q.db.ExecContext(ctx, UpdatePayslipStatusFailed, txHash)
	return err
}

const UpdateValidatorActionState = `-- name: UpdateValidatorActionState :exec
UPDATE validator_actions SET state = ?, updated_at = CURRENT_TIMESTAMP, error_summary = ? WHERE id = ?
`

type UpdateValidatorActionStateParams struct {
	State        sql.NullString `json:"state"`
	ErrorSummary sql.NullString `json:"error_summary"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateValidatorActionState(ctx context.Context, arg UpdateValidatorActionStateParams) error {
	_, err := q.db.ExecContext(ctx, UpdateValidatorActionState, arg.State, arg.ErrorSummary, arg.ID)
	return err
}

const UpsertCursor = `-- name: UpsertCursor :exec
INSERT INTO cursor (name, height) VALUES (?, ?)
ON CONFLICT (name) DO UPDATE SET height = excluded.height
`

type UpsertCursorParams struct {
	Name   string `json:"name"`
	Height int64  `json:"height"`
}

func (q *Queries) UpsertCursor(ctx context.Context, arg UpsertCursorParams) error {
	_, err := q.db.ExecContext(ctx, UpsertCursor, arg.Name, arg.Height)
	return err
}

const UpsertRuntimeStatus = `-- name: UpsertRuntimeStatus :exec
INSERT INTO runtime_status (id, heartbeat_at, daemon_version, config_hash, derived_validator_address, validator_state, last_processed_height, chain_head, last_tick_ms, rpc_ok, readiness_error)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET heartbeat_at=excluded.heartbeat_at, daemon_version=excluded.daemon_version, config_hash=excluded.config_hash, derived_validator_address=excluded.derived_validator_address, validator_state=excluded.validator_state, last_processed_height=excluded.last_processed_height, chain_head=excluded.chain_head, last_tick_ms=excluded.last_tick_ms, rpc_ok=excluded.rpc_ok, readiness_error=excluded.readiness_error
`

type UpsertRuntimeStatusParams struct {
	HeartbeatAt             time.Time      `json:"heartbeat_at"`
	DaemonVersion           string         `json:"daemon_version"`
	ConfigHash              string         `json:"config_hash"`
	DerivedValidatorAddress string         `json:"derived_validator_address"`
	ValidatorState          string         `json:"validator_state"`
	LastProcessedHeight     int64          `json:"last_processed_height"`
	ChainHead               int64          `json:"chain_head"`
	LastTickMs              int64          `json:"last_tick_ms"`
	RpcOk                   int64          `json:"rpc_ok"`
	ReadinessError          sql.NullString `json:"readiness_error"`
}

func (q *Queries) UpsertRuntimeStatus(ctx context.Context, arg UpsertRuntimeStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpsertRuntimeStatus,
		arg.HeartbeatAt,
		arg.DaemonVersion,
		arg.ConfigHash,
		arg.DerivedValidatorAddress,
		arg.ValidatorState,
		arg.LastProcessedHeight,
		arg.ChainHead,
		arg.LastTickMs,
		arg.RpcOk,
		arg.ReadinessError,
	)
	return err
}
